spring:
  application:
    name: currencies
  liquibase:
    enabled: true
    default-schema: currencies_schema
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/currencies
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: currencies_schema

external:
  api:
    baseurl: http://localhost:3001/api

scheduler:
  currency:
    fixedRate: 10000