version: '3.8'
services:
  db:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=currencies
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: currencies_stub_api
    ports:
      - "3001:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]
volumes:
  db:
    driver: local